jobs:
  - name: The job name
    tasks:
      - name: task 1
        workdir: .
        command: echo
        args:
          - run task1
        timeout: 10s
      - name: task 2
        workdir: .
        command: echo
        args:
          - run
          - task2
        timeout: 10s
      - name: task 3 will timeout
        workdir: .
        command: sleep
        args:
          - 5
        timeout: 1s
      - name: task 4 unreachable
        workdir: .
        command: echo
        args:
          - unreachable at this task
        timeout: 10s
